name: marketplace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  http: ^1.3.0
  image_picker: ^1.1.2
  geolocator: ^13.0.2
  provider: ^6.0.0
  socket_io_client: ^3.0.2
  shared_preferences: ^2.2.2
  carousel_slider: ^5.0.0
  http_parser: ^4.1.2
  flutter_dotenv: ^5.1.0
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
